apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: jenkins
type: Opaque
data:
  config.json: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkb2RvMTMzIiwicGFzc3dvcmQiOiJrYXkyNDEyNUAiLCJhdXRoIjoiWkc5a2J6RXpNenByWVhreU5ERXlOVUE9In19fQo=
  username: ZG9kbzEzMw==
  password: a2F5MjQxMjVA