apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deploykf-istio-gateway-certificate
  namespace: deploykf-istio-gateway
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  secretName: deploykf-istio-gateway-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - dkf-tw-style.duckdns.org
  - argo-server.dkf-tw-style.duckdns.org
  - minio-api.dkf-tw-style.duckdns.org
  - minio-console.dkf-tw-style.duckdns.org
