apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-gateway
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gateway
  template:
    metadata:
      labels:
        app: spring-gateway
    spec:
      containers:
      - name: gateway
        image: dodo133/prod_gateway_backend_spring_service:test-54c7aac4189c
        ports:
        - containerPort: 8080