apiVersion: v1
metadata:
  name: spring-gateway-configmap
  namespace: prod
kind: ConfigMap
data:
  service: spring-gateway-service
  application-gateway.properties: |
    server.port=8080
    spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-origins=https://tw-style.duckdns.org/
    spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods=GET,POST,PUT,DELETE
    spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-headers=Authorization,Content-Type
    spring.cloud.gateway.globalcors.cors-configurations[/**].allow-credentials=true
    spring.cloud.gateway.default-filters[0].name=GlobalFilter
    spring.cloud.gateway.default-filters[0].args.baseMessage=Spring Cloud Gateway GlobalFilter
    spring.cloud.gateway.default-filters[0].args.preLogger=true
    spring.cloud.gateway.default-filters[0].args.postLogger=true
    spring.cloud.gateway.routes[0].id=member-route
    spring.cloud.gateway.routes[0].uri=http://spring-member-service:8080/
    spring.cloud.gateway.routes[0].predicates=Path=/member/**
    spring.cloud.gateway.routes[0].filters[0].name=MemberFilter
    spring.cloud.gateway.routes[0].filters[0].args.baseMessage=Spring Cloud Gateway UserFilter
    spring.cloud.gateway.routes[0].filters[0].args.preLogger=true
    spring.cloud.gateway.routes[0].filters[0].args.postLogger=true
    spring.cloud.gateway.routes[1].id=video-route
    spring.cloud.gateway.routes[1].uri=http://spring-video-service:8080/
    spring.cloud.gateway.routes[1].predicates=Path=/video/**
    spring.cloud.gateway.routes[1].filters[0].name=VideoFilter
    spring.cloud.gateway.routes[1].filters[0].args.baseMessage=Spring Cloud Gateway VideoFilter
    spring.cloud.gateway.routes[1].filters[0].args.preLogger=true
    spring.cloud.gateway.routes[1].filters[0].args.postLogger=true
    management.endpoints.web.exposure.include=actuator,gateway
    google.client-id=585543292084-nglvej9fqvsm7in5bgev62scqbqpnllr.apps.googleusercontent.com
