apiVersion: apps/v1
kind: Deployment
metadata:
  name: tws-ai-cpu-deploy
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-cpu
  template:
    metadata:
      labels:
        app: ai-cpu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: driver
                operator: In
                values:
                - vulkan
      containers:
      - name: ai-cpu
        image: dodo133/tws-ai:test-b8b176f671dd
        # env:
        # - name: NVIDIA_VISIBLE_DEVICES
        #   value: "none"
        # image: test_ai_upscale_service
        ports:
        - containerPort: 8000