apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tw-style-duckdns-org-prod-certificate
  namespace: prod
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  secretName: tw-style-duckdns-org-prod-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - tw-style.duckdns.org
  - api.tw-style.duckdns.org
