apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  namespace: prod
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: tws-web-service
            port:
              number: 80