apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
      - name: react-service
        image: dodo133/react_service-dev:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: DOMAIN
          value: "tw-style.duckdns.org"
        - name: SSL_PORT
          value: "11910"
        - name: PORT
          value: "11911"
---
apiVersion: v1
kind: Service
metadata:
  name: react-service-service
spec:
  type: NodePort
  selector:
    app: react-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30010




# docker run --rm -p 11910:443 -p 11911:80 --env-file ./.env dodo133/react_service-dev