apiVersion: apps/v1
kind: Deployment
metadata:
  name: tws-web-deploy
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tws-web
  template:
    metadata:
      labels:
        app: tws-web
    spec:
      containers:
      - name: tws-web
        image: dodo133/react-test:latest
        ports:
        - containerPort: 80