apiVersion: v1
kind: Service
metadata:
  name: tws-web-service
  namespace: prod
spec:
  selector:
    app: tws-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443