version: "3"
services:
  certbot:
    build:
      context: .
    volumes:
      - certbot-etc:/etc/letsencrypt
    environment:
      - DOMAIN= tw-style.duckdns.org
      - EMAIL=pch14545@gmail.com

volumes:
  certbot-etc:
