apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config
  template:
    metadata:
      labels:
        app: spring-config
    spec:
      containers:
      - name: gateway
        image: dodo133/config_backend_spring_service:test-b3b957d5f334
        ports:
        - containerPort: 8080