apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "dockerhub credentials from Kubernetes"
type: Opaque
stringData:
  config.json: '{"auths":{"https://index.docker.io/v1/":{"username":"dodo133","password":"kay24125@","auth":"ZG9kbzEzMzprYXkyNDEyNUA="}}}'
  username: dodo133
  password: kay24125@