apiVersion: apps/v1
kind: Deployment
metadata:
  name: tws-ai-gpu-deploy
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tws-ai-gpu
  template:
    metadata:
      labels:
        app: ai-gpu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: driver
                operator: In
                values:
                - vulkan
      containers:
      - name: ai-gpu
        image: dodo133/tws-ai:gpu
        # env:
        # - name: NVIDIA_VISIBLE_DEVICES
        #   value: "none"
        # image: test_ai_upscale_service
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
