apiVersion: apps/v1
kind: Deployment
metadata:
  name: tws-spring-deploy
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tws-spring
  template:
    metadata:
      labels:
        app: tws-spring
    spec:
      containers:
      - name: config
        image: dodo133/config_backend_spring_service:latest
        ports:
        - containerPort: 9089

      - name: gateway
        image: dodo133/prod_gateway_backend_spring_service:test-c31bd20aeafb
        ports:
        - containerPort: 9090

      - name: member
        image: dodo133/prod_member_backend_spring_service:test-67ae9bcd1572
        ports:
        - containerPort: 9091

      - name: video
        image: dodo133/prod_video_backend_spring_service:test-4aa2132e81fa
        ports:
        - containerPort: 9092

      - name: email
        image: dodo133/prod_email_backend_spring_service:latest
        ports:
        - containerPort: 9093

      - name: test
        image: ubuntu:20.04
        command: ["/bin/sleep", "infinity"]
        ports:
        - containerPort: 9999
