version: '3.7'

services:
  jenkins:
    build: 
      context: .
    container_name: jenkins
    user: root
    ports:
      - 12590:8080
      - 12591:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    entrypoint: /bin/bash