version: '3.7'

services:
  jenkins:
    build: 
      context: .
    container_name: jenkins
    user: root
    ports:
      - 12590:8080
      # for master-slave system
      - 12591:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ssl_certbot-etc:/etc/letsencrypt:ro

volumes:
  ssl_certbot-etc:
    external: true
