apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-tw-style-duckdns-certificate
  namespace: dev
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  secretName: dev-tw-style-duckdns-tls-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - ag.dev-tw-style.duckdns.org
  - jk.dev-tw-style.duckdns.org
  # - pm.dev-tw-style.duckdns.org
  # - gf.dev-tw-style.duckdns.org
  - dkf.dev-tw-style.duckdns.org
  # - kf.dev-tw-style.duckdns.org
  # - mf.dev-tw-style.duckdns.org
