name: Deploy Secrets

on:
  push:
    paths:
      - '.github/workflows/deploy-secrets.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Check for the latest version

    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3  # Check for the latest version, if available
      with:
        version: 'latest'

    - name: Configure Kubernetes Context
      uses: Azure/k8s-set-context@v3  # Check for the latest version, if available
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy Secret1 to Kubernetes
      run: |
        echo "${{ secrets.SECRET_TEST }}" | kubectl create secret generic test-secret --from-file=test-secret-key=/dev/stdin --dry-run=client -o yaml | kubectl apply -f -

    # - name: Deploy Secret2 to Kubernetes
    #   run: |
    #     echo "${{ secrets.SECRET2_DATA }}" | kubectl create secret generic secret2 --from-file=secret2-data=/dev/stdin --dry-run=client -o yaml | kubectl apply -f -
